<?php
/**
 * Grammar error-spotting item bank.
 *
 * A companion to `GrammarBank`, not a replacement: `GrammarQuiz` asks the
 * learner to fill a blank correctly, which tests recognising a correct form
 * among options. This bank instead presents a complete, fluent-looking
 * sentence with exactly one deliberate mistake already in it and asks the
 * learner to find *which part* is wrong — a different and, for many
 * learners, harder skill: spotting an error that doesn't announce itself
 * with a blank.
 *
 * Each item is a sentence split into segments (the natural phrase chunks a
 * reader would parse it in); exactly one segment contains the mistake. The
 * segments, joined with spaces, must read as a complete, grammatical-looking
 * sentence except for that one error — there is no separate "correct
 * version" stored, since the explanation states the fix in prose the same
 * way `GrammarBank`'s explanations already do.
 *
 * Unlike `GrammarBank`'s deliberate A1-B1 cap, this bank runs the full A1-C2
 * range — the same reasoning `SentenceBank` used to extend past B1. The A1-B1
 * cap was never about level itself; it was about specific grammar *points*
 * (mixed conditionals, the subjunctive, reported-speech nuance) carrying
 * genuine native-speaker disagreement above B1, which a single-answer check
 * cannot fairly adjudicate. What's tested at B2-C2 here — passive voice,
 * reported speech, real (non-mixed) conditionals, relative-clause pronoun
 * choice, plus harder instances of the original eight points — stays just as
 * unambiguous as the A1-B1 material; only the sentence complexity rises.
 *
 * Thirty-six items per level since 1.16.0 (twelve before, and originally five
 * per topic-level at A1-B1 only). Twelve only just exceeded
 * `ErrorCorrection::SESSION_LENGTH` (10), so a learner's second session was
 * mostly repeats; 36 gives more than three fresh sessions per level. The
 * 1.16.0 blocks at the end follow the same rules, and prefer errors that can
 * only sit in one segment (a wrong irregular form, a wrong preposition after a
 * fixed word) over ones a learner could "fix" somewhere else in the sentence.
 * They add topics beyond the original twelve (plurals, pronouns, question
 * forms, gerunds/infinitives, linking words, negatives, inversion). One
 * original item, quant-err-7, was rewritten in 1.16.0: "Neither of the
 * answers were correct" is widely accepted, so it no longer counts as wrong.
 *
 * @package EnglishFindersStudy
 */

declare(strict_types=1);

namespace EnglishFindersStudy\Tools;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

final class ErrorBank {
	/**
	 * @return list<array{id:string,topic:string,level:string,segments:list<string>,error_index:int,explanation:string}>
	 */
	public static function items(): array {
		return array(
			// --- Articles ---------------------------------------------------
			array(
				'id'           => 'art-err-1',
				'topic'        => 'articles',
				'level'        => 'A1',
				'segments'     => array( 'She', 'is', 'a', 'engineer.' ),
				'error_index'  => 2,
				'explanation'  => '"Engineer" starts with a vowel sound, so this should be "an", not "a".',
			),
			array(
				'id'           => 'art-err-4',
				'topic'        => 'articles',
				'level'        => 'A1',
				'segments'     => array( 'I', 'saw', 'a', 'elephant', 'at', 'the', 'zoo.' ),
				'error_index'  => 2,
				'explanation'  => '"Elephant" begins with a vowel sound, so this should be "an", not "a".',
			),
			array(
				'id'           => 'art-err-2',
				'topic'        => 'articles',
				'level'        => 'A2',
				'segments'     => array( 'He plays', 'a', 'guitar', 'every evening.' ),
				'error_index'  => 1,
				'explanation'  => '"The" is used before a musical instrument after "play": "play the guitar", not "a guitar".',
			),
			array(
				'id'           => 'art-err-3',
				'topic'        => 'articles',
				'level'        => 'B1',
				'segments'     => array( 'I need', 'an advice', 'about my career.' ),
				'error_index'  => 1,
				'explanation'  => '"Advice" is uncountable, so it takes no article here — just "advice", not "an advice".',
			),
			array(
				'id'           => 'art-err-5',
				'topic'        => 'articles',
				'level'        => 'B1',
				'segments'     => array( 'I need', 'a information', 'about the course.' ),
				'error_index'  => 1,
				'explanation'  => '"Information" is uncountable, so it takes no article here — just "information", not "a information".',
			),
			array(
				'id'           => 'art-err-6',
				'topic'        => 'articles',
				'level'        => 'B2',
				'segments'     => array( 'I bought', 'a furniture', 'for my new apartment.' ),
				'error_index'  => 1,
				'explanation'  => '"Furniture" is uncountable, so it takes no article — just "furniture", not "a furniture".',
			),
			array(
				'id'           => 'art-err-7',
				'topic'        => 'articles',
				'level'        => 'B2',
				'segments'     => array( 'He', 'is', 'an', 'university', 'professor.' ),
				'error_index'  => 2,
				'explanation'  => '"University" starts with a consonant *sound* (/j/), so it takes "a", not "an", despite starting with a vowel letter.',
			),
			array(
				'id'           => 'art-err-8',
				'topic'        => 'articles',
				'level'        => 'C2',
				'segments'     => array( 'He', 'has', 'an', 'one-year', 'contract', 'with', 'the', 'company.' ),
				'error_index'  => 2,
				'explanation'  => '"One" is pronounced with a consonant sound (/w/), so it takes "a", not "an", despite the spelling.',
			),

			// --- Prepositions -------------------------------------------------
			array(
				'id'           => 'prep-err-1',
				'topic'        => 'prepositions',
				'level'        => 'A1',
				'segments'     => array( 'The meeting is', 'in', 'Monday.' ),
				'error_index'  => 1,
				'explanation'  => 'Days of the week take "on": "on Monday", not "in Monday".',
			),
			array(
				'id'           => 'prep-err-4',
				'topic'        => 'prepositions',
				'level'        => 'A1',
				'segments'     => array( 'I', 'wake', 'up', 'on', '7', 'o\'clock.' ),
				'error_index'  => 3,
				'explanation'  => 'Clock times take "at": "at 7 o\'clock", not "on 7 o\'clock".',
			),
			array(
				'id'           => 'prep-err-2',
				'topic'        => 'prepositions',
				'level'        => 'A2',
				'segments'     => array( 'She lives', 'at', 'Paris.' ),
				'error_index'  => 1,
				'explanation'  => 'Cities and countries take "in": "in Paris", not "at Paris".',
			),
			array(
				'id'           => 'prep-err-3',
				'topic'        => 'prepositions',
				'level'        => 'B1',
				'segments'     => array( 'He arrived', 'to', 'the airport', 'an hour early.' ),
				'error_index'  => 1,
				'explanation'  => '"At" is used for a specific point or building, such as an airport: "arrived at the airport".',
			),
			array(
				'id'           => 'prep-err-5',
				'topic'        => 'prepositions',
				'level'        => 'B1',
				'segments'     => array( 'She', 'has been', 'working', 'here', 'since', 'five', 'years.' ),
				'error_index'  => 4,
				'explanation'  => '"For" is used with a length of time ("for five years"); "since" marks a starting point in time, not a duration.',
			),
			array(
				'id'           => 'prep-err-6',
				'topic'        => 'prepositions',
				'level'        => 'B2',
				'segments'     => array( 'She', 'apologized', 'about', 'being', 'late.' ),
				'error_index'  => 2,
				'explanation'  => '"Apologize" is followed by "for", not "about": "apologized for being late".',
			),
			array(
				'id'           => 'prep-err-7',
				'topic'        => 'prepositions',
				'level'        => 'C2',
				'segments'     => array( 'The', 'court', 'ruled', 'against of', 'the', 'defendant.' ),
				'error_index'  => 3,
				'explanation'  => '"Rule against" is followed directly by its object, with no extra preposition: "ruled against the defendant", not "ruled against of the defendant".',
			),

			// --- Present tense --------------------------------------------
			array(
				'id'           => 'pres-err-1',
				'topic'        => 'present-tense',
				'level'        => 'A1',
				'segments'     => array( 'She', 'go', 'to school', 'every day.' ),
				'error_index'  => 1,
				'explanation'  => 'Present simple with "she" (third person singular) adds -s: "she goes", not "she go".',
			),
			array(
				'id'           => 'pres-err-4',
				'topic'        => 'present-tense',
				'level'        => 'A1',
				'segments'     => array( 'Look!', 'It', 'rain', 'outside.' ),
				'error_index'  => 2,
				'explanation'  => 'Something happening right now uses the present continuous: "is raining", not "rain".',
			),
			array(
				'id'           => 'pres-err-2',
				'topic'        => 'present-tense',
				'level'        => 'A2',
				'segments'     => array( 'They', 'plays', 'football', 'at the moment.' ),
				'error_index'  => 1,
				'explanation'  => '"At the moment" signals the present continuous: "are playing", not "plays".',
			),
			array(
				'id'           => 'pres-err-3',
				'topic'        => 'present-tense',
				'level'        => 'B1',
				'segments'     => array( 'Water', 'boil', 'at 100 degrees', 'Celsius.' ),
				'error_index'  => 1,
				'explanation'  => 'A general fact uses the present simple, and "water" is singular, so it takes "boils", not "boil".',
			),
			array(
				'id'           => 'pres-err-5',
				'topic'        => 'present-tense',
				'level'        => 'B1',
				'segments'     => array( 'He', 'always', 'forget', 'his', 'keys.' ),
				'error_index'  => 2,
				'explanation'  => 'Present simple with "he" (third person singular) adds -s: "forgets", not "forget".',
			),
			array(
				'id'           => 'pres-err-6',
				'topic'        => 'present-tense',
				'level'        => 'C1',
				'segments'     => array( 'By', 'next', 'year,', 'she', 'will', 'has', 'completed', 'her', 'degree.' ),
				'error_index'  => 5,
				'explanation'  => 'After "will", the verb stays in its base form: "will have completed" (future perfect), not "will has completed".',
			),

			// --- Past tense -------------------------------------------------
			array(
				'id'           => 'past-err-1',
				'topic'        => 'past-tense',
				'level'        => 'A1',
				'segments'     => array( 'Yesterday,', 'I', 'go', 'to the market.' ),
				'error_index'  => 2,
				'explanation'  => '"Yesterday" needs the past simple: "went", not "go".',
			),
			array(
				'id'           => 'past-err-4',
				'topic'        => 'past-tense',
				'level'        => 'A1',
				'segments'     => array( 'She', 'finish', 'her', 'homework', 'last', 'night.' ),
				'error_index'  => 1,
				'explanation'  => '"Last night" needs the past simple: "finished", not "finish".',
			),
			array(
				'id'           => 'past-err-2',
				'topic'        => 'past-tense',
				'level'        => 'A2',
				'segments'     => array( 'He was born', 'on', '1998.' ),
				'error_index'  => 1,
				'explanation'  => 'A year takes "in": "born in 1998", not "born on 1998".',
			),
			array(
				'id'           => 'past-err-3',
				'topic'        => 'past-tense',
				'level'        => 'B1',
				'segments'     => array( 'I have', 'saw', 'that movie', 'already.' ),
				'error_index'  => 1,
				'explanation'  => 'The present perfect needs the past participle: "have seen", not "have saw".',
			),
			array(
				'id'           => 'past-err-5',
				'topic'        => 'past-tense',
				'level'        => 'B1',
				'segments'     => array( 'I', 'have seen', 'him', 'yesterday.' ),
				'error_index'  => 1,
				'explanation'  => 'A specific past time word like "yesterday" needs the past simple: "saw", not the present perfect "have seen".',
			),
			array(
				'id'           => 'past-err-6',
				'topic'        => 'past-tense',
				'level'        => 'C1',
				'segments'     => array( 'By', 'the time', 'the', 'police', 'arrived,', 'the thief', 'has', 'already', 'escaped.' ),
				'error_index'  => 6,
				'explanation'  => 'An earlier past event relative to another past event needs the past perfect: "had already escaped", not "has already escaped".',
			),

			// --- Comparatives -------------------------------------------------
			array(
				'id'           => 'comp-err-1',
				'topic'        => 'comparatives',
				'level'        => 'A1',
				'segments'     => array( 'This book is', 'interestinger', 'than that one.' ),
				'error_index'  => 1,
				'explanation'  => 'Longer adjectives form the comparative with "more": "more interesting", not "interestinger".',
			),
			array(
				'id'           => 'comp-err-2',
				'topic'        => 'comparatives',
				'level'        => 'A2',
				'segments'     => array( 'She is the', 'goodest', 'student in the class.' ),
				'error_index'  => 1,
				'explanation'  => '"Good" has an irregular superlative: "best", not "goodest".',
			),
			array(
				'id'           => 'comp-err-4',
				'topic'        => 'comparatives',
				'level'        => 'A2',
				'segments'     => array( 'This is', 'baddest', 'film I have ever seen.' ),
				'error_index'  => 1,
				'explanation'  => '"Bad" has an irregular superlative, "the worst", used with "ever" for an extreme comparison.',
			),
			array(
				'id'           => 'comp-err-3',
				'topic'        => 'comparatives',
				'level'        => 'B1',
				'segments'     => array( 'My phone is', 'more cheap', 'than yours.' ),
				'error_index'  => 1,
				'explanation'  => 'Short adjectives like "cheap" take -er rather than "more": "cheaper", not "more cheap".',
			),
			array(
				'id'           => 'comp-err-5',
				'topic'        => 'comparatives',
				'level'        => 'B2',
				'segments'     => array( 'The', 'more', 'you', 'practice,', 'the', 'better', 'you will', 'became.' ),
				'error_index'  => 7,
				'explanation'  => 'After "will", the verb stays in its base form: "will become", not "will became".',
			),
			array(
				'id'           => 'comp-err-6',
				'topic'        => 'comparatives',
				'level'        => 'C2',
				'segments'     => array( 'The', 'situation', 'is', 'becoming', 'more and more', 'worst.' ),
				'error_index'  => 5,
				'explanation'  => '"More and more" pairs with the comparative "worse", not the superlative "worst".',
			),

			// --- Subject-verb agreement -----------------------------------
			array(
				'id'           => 'agr-err-1',
				'topic'        => 'agreement',
				'level'        => 'A1',
				'segments'     => array( 'He', 'are', 'a teacher.' ),
				'error_index'  => 1,
				'explanation'  => '"He" takes the singular form "is", not "are".',
			),
			array(
				'id'           => 'agr-err-2',
				'topic'        => 'agreement',
				'level'        => 'A2',
				'segments'     => array( 'The news', 'are', 'surprising.' ),
				'error_index'  => 1,
				'explanation'  => '"News" looks plural but is grammatically singular: "the news is", not "the news are".',
			),
			array(
				'id'           => 'agr-err-4',
				'topic'        => 'agreement',
				'level'        => 'A2',
				'segments'     => array( 'My', 'glasses', 'is', 'on', 'the', 'desk.' ),
				'error_index'  => 2,
				'explanation'  => '"Glasses" (like trousers, scissors) is treated as plural: "the glasses are", not "is".',
			),
			array(
				'id'           => 'agr-err-3',
				'topic'        => 'agreement',
				'level'        => 'B1',
				'segments'     => array( 'Everyone', 'are', 'invited to the party.' ),
				'error_index'  => 1,
				'explanation'  => 'Indefinite pronouns like "everyone" take a singular verb: "everyone is", not "everyone are".',
			),
			array(
				'id'           => 'agr-err-5',
				'topic'        => 'agreement',
				'level'        => 'C1',
				'segments'     => array( 'A', 'number', 'of', 'issues', 'has', 'been', 'raised.' ),
				'error_index'  => 4,
				'explanation'  => '"A number of + plural noun" takes a plural verb: "a number of issues have been raised", not "has".',
			),
			array(
				'id'           => 'agr-err-6',
				'topic'        => 'agreement',
				'level'        => 'C2',
				'segments'     => array( 'Mathematics', 'were', 'her', 'favourite', 'subject', 'at', 'school.' ),
				'error_index'  => 1,
				'explanation'  => 'Academic subject names ending in "-ics" (mathematics, physics, economics) are grammatically singular: "mathematics was", not "were".',
			),

			// --- Modals -------------------------------------------------------
			array(
				'id'           => 'mod-err-1',
				'topic'        => 'modals',
				'level'        => 'A1',
				'segments'     => array( 'You', 'can', 'eat', 'in the library.' ),
				'error_index'  => 1,
				'explanation'  => 'A prohibition needs "mustn\'t" ("not allowed"), not "can": "you mustn\'t eat in the library".',
			),
			array(
				'id'           => 'mod-err-2',
				'topic'        => 'modals',
				'level'        => 'A2',
				'segments'     => array( 'You should', 'to see', 'a doctor', 'if the pain continues.' ),
				'error_index'  => 1,
				'explanation'  => 'Modal verbs like "should" are followed by the bare infinitive: "should see", not "should to see".',
			),
			array(
				'id'           => 'mod-err-4',
				'topic'        => 'modals',
				'level'        => 'A2',
				'segments'     => array( 'Can', 'I', 'opens', 'the', 'window?' ),
				'error_index'  => 2,
				'explanation'  => 'After the modal "can", the verb stays in its base form: "can I open", not "can I opens".',
			),
			array(
				'id'           => 'mod-err-3',
				'topic'        => 'modals',
				'level'        => 'B1',
				'segments'     => array( 'You should have', 'call', 'me — I was worried!' ),
				'error_index'  => 1,
				'explanation'  => '"Should have" is followed by a past participle: "should have called", not "should have call".',
			),
			array(
				'id'           => 'mod-err-5',
				'topic'        => 'modals',
				'level'        => 'B2',
				'segments'     => array( 'He', 'must', 'has', 'left', 'already.' ),
				'error_index'  => 2,
				'explanation'  => 'After the modal "must", the verb stays in its base form: "must have left", not "must has left".',
			),
			array(
				'id'           => 'mod-err-6',
				'topic'        => 'modals',
				'level'        => 'C1',
				'segments'     => array( 'He', 'needn\'t to', 'have', 'worried', 'about', 'the', 'exam.' ),
				'error_index'  => 1,
				'explanation'  => 'A modal like "needn\'t" is followed directly by the bare infinitive, with no "to": "needn\'t have worried", not "needn\'t to have worried".',
			),

			// --- Quantifiers ----------------------------------------------
			array(
				'id'           => 'quant-err-1',
				'topic'        => 'quantifiers',
				'level'        => 'A1',
				'segments'     => array( 'There is', 'many', 'milk', 'in the fridge.' ),
				'error_index'  => 1,
				'explanation'  => '"Milk" is uncountable, so it takes "much", not "many": "much milk".',
			),
			array(
				'id'           => 'quant-err-2',
				'topic'        => 'quantifiers',
				'level'        => 'A2',
				'segments'     => array( 'How', 'much', 'apples', 'do you want?' ),
				'error_index'  => 1,
				'explanation'  => '"Apples" is countable, so the question uses "many": "how many apples", not "how much apples".',
			),
			array(
				'id'           => 'quant-err-4',
				'topic'        => 'quantifiers',
				'level'        => 'A2',
				'segments'     => array( 'I', 'have', 'much', 'friends', 'in', 'this', 'city.' ),
				'error_index'  => 2,
				'explanation'  => '"Friends" is countable, so this needs "a few", not "much".',
			),
			array(
				'id'           => 'quant-err-3',
				'topic'        => 'quantifiers',
				'level'        => 'B1',
				'segments'     => array( 'Very', 'little', 'people', 'know about this place.' ),
				'error_index'  => 1,
				'explanation'  => '"People" is countable, so this needs "few", not "little": "very few people".',
			),
			array(
				'id'           => 'quant-err-5',
				'topic'        => 'quantifiers',
				'level'        => 'B2',
				'segments'     => array( 'There', 'were', 'fewer', 'information', 'than', 'expected.' ),
				'error_index'  => 2,
				'explanation'  => '"Information" is uncountable, so it takes "less", not "fewer".',
			),
			array(
				'id'           => 'quant-err-6',
				'topic'        => 'quantifiers',
				'level'        => 'C1',
				'segments'     => array( 'Each', 'of', 'the', 'students', 'have', 'submitted', 'their', 'essay.' ),
				'error_index'  => 4,
				'explanation'  => '"Each of + plural noun" takes a singular verb: "each of the students has submitted", not "have".',
			),
			array(
				'id'           => 'quant-err-7',
				'topic'        => 'quantifiers',
				'level'        => 'C1',
				'segments'     => array( 'Neither', 'candidate', 'were', 'suitable', 'for the role.' ),
				'error_index'  => 2,
				'explanation'  => '"Neither" + a singular noun takes a singular verb: "Neither candidate was suitable", not "were".',
			),

			// --- Passive voice --------------------------------------------
			array(
				'id'           => 'passive-err-1',
				'topic'        => 'passive-voice',
				'level'        => 'B2',
				'segments'     => array( 'The', 'bridge', 'was', 'build', 'in', '1990.' ),
				'error_index'  => 3,
				'explanation'  => 'The passive voice needs the past participle: "was built", not "was build".',
			),
			array(
				'id'           => 'passive-err-2',
				'topic'        => 'passive-voice',
				'level'        => 'B2',
				'segments'     => array( 'New', 'employees', 'are', 'gave', 'a', 'handbook', 'on', 'their', 'first', 'day.' ),
				'error_index'  => 3,
				'explanation'  => 'The passive voice needs the past participle: "are given", not "are gave".',
			),
			array(
				'id'           => 'passive-err-3',
				'topic'        => 'passive-voice',
				'level'        => 'C1',
				'segments'     => array( 'The', 'proposal', 'is', 'being', 'considering', 'by', 'the', 'board.' ),
				'error_index'  => 4,
				'explanation'  => 'The passive continuous needs a past participle: "is being considered", not "is being considering".',
			),
			array(
				'id'           => 'passive-err-4',
				'topic'        => 'passive-voice',
				'level'        => 'C2',
				'segments'     => array( 'The', 'report', 'ought', 'to', 'have', 'been', 'finish', 'before', 'the', 'deadline.' ),
				'error_index'  => 6,
				'explanation'  => 'The passive needs a past participle: "have been finished", not "have been finish".',
			),
			array(
				'id'           => 'passive-err-5',
				'topic'        => 'passive-voice',
				'level'        => 'C2',
				'segments'     => array( 'Mistakes', 'were', 'made,', 'but', 'no', 'one', 'was', 'hold', 'accountable.' ),
				'error_index'  => 7,
				'explanation'  => 'The passive voice needs the past participle: "was held accountable", not "was hold accountable".',
			),

			// --- Reported speech --------------------------------------------
			array(
				'id'           => 'reported-err-1',
				'topic'        => 'reported-speech',
				'level'        => 'B2',
				'segments'     => array( 'She', 'said', 'that', 'she', 'is', 'tired.' ),
				'error_index'  => 4,
				'explanation'  => 'Reported speech in the past shifts the tense back: "she was tired", not "she is tired".',
			),
			array(
				'id'           => 'reported-err-2',
				'topic'        => 'reported-speech',
				'level'        => 'C1',
				'segments'     => array( 'He', 'told me', 'that', 'he', 'will', 'call', 'me', 'the', 'next', 'day.' ),
				'error_index'  => 4,
				'explanation'  => 'Reported speech shifts "will" back to "would": "he would call", not "he will call".',
			),
			array(
				'id'           => 'reported-err-3',
				'topic'        => 'reported-speech',
				'level'        => 'C1',
				'segments'     => array( 'She', 'asked', 'me', 'where', 'I', 'did live.' ),
				'error_index'  => 5,
				'explanation'  => 'A reported question keeps normal statement word order and the past simple, not "did" + base verb: "where I lived", not "where I did live".',
			),
			array(
				'id'           => 'reported-err-4',
				'topic'        => 'reported-speech',
				'level'        => 'C2',
				'segments'     => array( 'She', 'wondered', 'whether', 'she', 'should', 'have', 'went', 'earlier.' ),
				'error_index'  => 6,
				'explanation'  => '"Should have" is followed by a past participle: "should have gone", not "should have went".',
			),
			array(
				'id'           => 'reported-err-5',
				'topic'        => 'reported-speech',
				'level'        => 'C2',
				'segments'     => array( 'He', 'admitted', 'that', 'he', 'has', 'lied', 'about', 'his', 'qualifications.' ),
				'error_index'  => 4,
				'explanation'  => 'The lying happened before the admitting, so reported speech needs the past perfect: "he had lied", not "he has lied".',
			),

			// --- Conditionals -------------------------------------------------
			array(
				'id'           => 'cond-err-1',
				'topic'        => 'conditionals',
				'level'        => 'B2',
				'segments'     => array( 'If', 'I', 'will have', 'time,', 'I will', 'help', 'you.' ),
				'error_index'  => 2,
				'explanation'  => 'The "if" clause of a first conditional uses the present simple, not "will": "If I have time", not "If I will have time".',
			),
			array(
				'id'           => 'cond-err-2',
				'topic'        => 'conditionals',
				'level'        => 'B2',
				'segments'     => array( 'If', 'it', 'rains', 'tomorrow,', 'we', 'would', 'cancel', 'the', 'picnic.' ),
				'error_index'  => 5,
				'explanation'  => 'A first conditional result clause uses "will", not "would": "we will cancel".',
			),
			array(
				'id'           => 'cond-err-3',
				'topic'        => 'conditionals',
				'level'        => 'C1',
				'segments'     => array( 'If she', 'had', 'studied', 'harder,', 'she', 'would pass', 'the', 'exam.' ),
				'error_index'  => 5,
				'explanation'  => 'A third conditional result clause needs "would have + past participle": "would have passed", not "would pass".',
			),
			array(
				'id'           => 'cond-err-4',
				'topic'        => 'conditionals',
				'level'        => 'C2',
				'segments'     => array( 'Had I', 'known', 'you', 'were', 'coming,', 'I', 'will', 'have', 'prepared', 'dinner.' ),
				'error_index'  => 6,
				'explanation'  => 'A third conditional result clause needs "would have", not "will have": "I would have prepared dinner".',
			),
			array(
				'id'           => 'cond-err-5',
				'topic'        => 'conditionals',
				'level'        => 'C2',
				'segments'     => array( 'If he', 'had', 'listened', 'to', 'advice,', 'he', 'wouldn\'t lost', 'his', 'job.' ),
				'error_index'  => 6,
				'explanation'  => 'A third conditional result clause needs "would(n\'t) have + past participle": "wouldn\'t have lost", not "wouldn\'t lost".',
			),

			// --- Relative clauses -------------------------------------------
			array(
				'id'           => 'rel-err-1',
				'topic'        => 'relative-clauses',
				'level'        => 'B2',
				'segments'     => array( 'The', 'man', 'which', 'called', 'you', 'is', 'my', 'uncle.' ),
				'error_index'  => 2,
				'explanation'  => '"Who" (not "which") is used for people in a relative clause.',
			),
			array(
				'id'           => 'rel-err-2',
				'topic'        => 'relative-clauses',
				'level'        => 'C1',
				'segments'     => array( 'The', 'company,', 'that', 'was', 'founded', 'in', '1990,', 'is', 'now', 'global.' ),
				'error_index'  => 2,
				'explanation'  => 'A non-defining relative clause (set off by commas) uses "which", not "that": "the company, which was founded in 1990,".',
			),
			array(
				'id'           => 'rel-err-3',
				'topic'        => 'relative-clauses',
				'level'        => 'C1',
				'segments'     => array( 'The', 'reason', 'of which', 'he', 'left', 'was', 'never', 'explained.' ),
				'error_index'  => 2,
				'explanation'  => 'The fixed phrase is "the reason for which", not "the reason of which".',
			),
			array(
				'id'           => 'rel-err-4',
				'topic'        => 'relative-clauses',
				'level'        => 'C2',
				'segments'     => array( 'The', 'evidence,', 'on that', 'the', 'verdict', 'was based,', 'was', 'later', 'questioned.' ),
				'error_index'  => 2,
				'explanation'  => 'A relative pronoun following a preposition must be "which" (or "whom" for people), never "that": "on which the verdict was based".',
			),
			array(
				'id'           => 'rel-err-5',
				'topic'        => 'relative-clauses',
				'level'        => 'C2',
				'segments'     => array( 'This', 'is', 'the', 'hotel', 'where', 'we', 'stayed there', 'last', 'year.' ),
				'error_index'  => 6,
				'explanation'  => '"Where" already supplies the location, so the resumptive "there" is redundant: "where we stayed", not "where we stayed there".',
			),

			// --- 1.16.0 expansion: A1  --------------------
			array(
				'id'           => 'err-a1-1',
				'topic'        => 'plurals',
				'level'        => 'A1',
				'segments'     => array( 'I', 'have', 'two', 'childs.' ),
				'error_index'  => 3,
				'explanation'  => 'The plural of "child" is irregular: "children", not "childs".',
			),
			array(
				'id'           => 'err-a1-2',
				'topic'        => 'plurals',
				'level'        => 'A1',
				'segments'     => array( 'There are', 'three', 'boxs', 'on the table.' ),
				'error_index'  => 2,
				'explanation'  => 'Nouns ending in -x add -es in the plural: "boxes".',
			),
			array(
				'id'           => 'err-a1-3',
				'topic'        => 'past-tense',
				'level'        => 'A1',
				'segments'     => array( 'Last week,', 'we', 'buyed', 'a new car.' ),
				'error_index'  => 2,
				'explanation'  => '"Buy" is irregular: its past simple is "bought", not "buyed".',
			),
			array(
				'id'           => 'err-a1-4',
				'topic'        => 'past-tense',
				'level'        => 'A1',
				'segments'     => array( 'He', 'goed', 'to the park', 'yesterday.' ),
				'error_index'  => 1,
				'explanation'  => '"Go" is irregular: its past simple is "went", not "goed".',
			),
			array(
				'id'           => 'err-a1-5',
				'topic'        => 'present-tense',
				'level'        => 'A1',
				'segments'     => array( 'My sister', 'have', 'a red bike.' ),
				'error_index'  => 1,
				'explanation'  => 'With a singular subject like "my sister", use "has", not "have".',
			),
			array(
				'id'           => 'err-a1-6',
				'topic'        => 'present-tense',
				'level'        => 'A1',
				'segments'     => array( 'My father', 'watchs', 'TV', 'every evening.' ),
				'error_index'  => 1,
				'explanation'  => 'Verbs ending in -ch add -es for he/she/it: "watches".',
			),
			array(
				'id'           => 'err-a1-7',
				'topic'        => 'present-tense',
				'level'        => 'A1',
				'segments'     => array( 'She', 'don’t', 'like', 'fish.' ),
				'error_index'  => 1,
				'explanation'  => 'With he/she/it, the negative is "doesn’t": "She doesn’t like fish."',
			),
			array(
				'id'           => 'err-a1-8',
				'topic'        => 'articles',
				'level'        => 'A1',
				'segments'     => array( 'I have', 'a', 'orange', 'for lunch.' ),
				'error_index'  => 1,
				'explanation'  => '"Orange" begins with a vowel sound, so it needs "an", not "a".',
			),
			array(
				'id'           => 'err-a1-9',
				'topic'        => 'articles',
				'level'        => 'A1',
				'segments'     => array( 'She', 'is', 'an', 'teacher.' ),
				'error_index'  => 2,
				'explanation'  => '"Teacher" begins with a consonant sound, so it needs "a", not "an".',
			),
			array(
				'id'           => 'err-a1-10',
				'topic'        => 'prepositions',
				'level'        => 'A1',
				'segments'     => array( 'My birthday', 'is', 'on', 'June.' ),
				'error_index'  => 2,
				'explanation'  => 'Months take "in": "in June", not "on June".',
			),
			array(
				'id'           => 'err-a1-11',
				'topic'        => 'prepositions',
				'level'        => 'A1',
				'segments'     => array( 'We', 'go', 'to bed', 'in', 'night.' ),
				'error_index'  => 3,
				'explanation'  => 'The fixed expression is "at night", not "in night".',
			),
			array(
				'id'           => 'err-a1-12',
				'topic'        => 'comparatives',
				'level'        => 'A1',
				'segments'     => array( 'My brother', 'is', 'more tall', 'than me.' ),
				'error_index'  => 2,
				'explanation'  => 'Short adjectives add -er: "taller", not "more tall".',
			),
			array(
				'id'           => 'err-a1-13',
				'topic'        => 'comparatives',
				'level'        => 'A1',
				'segments'     => array( 'This bag', 'is', 'biger', 'than that one.' ),
				'error_index'  => 2,
				'explanation'  => '"Big" doubles its last letter before -er: "bigger", not "biger".',
			),
			array(
				'id'           => 'err-a1-14',
				'topic'        => 'agreement',
				'level'        => 'A1',
				'segments'     => array( 'They', 'is', 'my', 'best friends.' ),
				'error_index'  => 1,
				'explanation'  => '"They" takes "are", not "is".',
			),
			array(
				'id'           => 'err-a1-15',
				'topic'        => 'agreement',
				'level'        => 'A1',
				'segments'     => array( 'I', 'is', 'ten years old.' ),
				'error_index'  => 1,
				'explanation'  => '"I" takes "am", not "is".',
			),
			array(
				'id'           => 'err-a1-16',
				'topic'        => 'modals',
				'level'        => 'A1',
				'segments'     => array( 'She', 'can', 'swims', 'very well.' ),
				'error_index'  => 2,
				'explanation'  => 'After "can", use the base verb: "can swim", not "can swims".',
			),
			array(
				'id'           => 'err-a1-17',
				'topic'        => 'modals',
				'level'        => 'A1',
				'segments'     => array( 'I', 'can to', 'speak', 'French.' ),
				'error_index'  => 1,
				'explanation'  => '"Can" is followed by the base verb without "to": "I can speak French."',
			),
			array(
				'id'           => 'err-a1-18',
				'topic'        => 'quantifiers',
				'level'        => 'A1',
				'segments'     => array( 'How', 'much', 'brothers', 'do you have?' ),
				'error_index'  => 1,
				'explanation'  => '"Brothers" is a plural countable noun, so ask "how many", not "how much".',
			),
			array(
				'id'           => 'err-a1-19',
				'topic'        => 'pronouns',
				'level'        => 'A1',
				'segments'     => array( 'Me', 'am', 'from Brazil.' ),
				'error_index'  => 0,
				'explanation'  => 'The subject of a sentence needs "I", not "me".',
			),
			array(
				'id'           => 'err-a1-20',
				'topic'        => 'pronouns',
				'level'        => 'A1',
				'segments'     => array( 'This is', 'my sister.', 'His', 'name', 'is Anna.' ),
				'error_index'  => 2,
				'explanation'  => 'For a girl or woman, the possessive is "her", not "his": "Her name is Anna."',
			),
			array(
				'id'           => 'err-a1-21',
				'topic'        => 'pronouns',
				'level'        => 'A1',
				'segments'     => array( 'I like Maria.', 'I', 'play', 'with', 'she', 'every day.' ),
				'error_index'  => 4,
				'explanation'  => 'After a preposition, use the object pronoun: "with her", not "with she".',
			),
			array(
				'id'           => 'err-a1-22',
				'topic'        => 'past-tense',
				'level'        => 'A1',
				'segments'     => array( 'We', 'was', 'at home', 'yesterday.' ),
				'error_index'  => 1,
				'explanation'  => 'The past of "be" with "we" is "were", not "was".',
			),
			array(
				'id'           => 'err-a1-23',
				'topic'        => 'plurals',
				'level'        => 'A1',
				'segments'     => array( 'I', 'brush', 'my', 'tooths', 'every morning.' ),
				'error_index'  => 3,
				'explanation'  => 'The plural of "tooth" is irregular: "teeth", not "tooths".',
			),
			array(
				'id'           => 'err-a1-24',
				'topic'        => 'verb-forms',
				'level'        => 'A1',
				'segments'     => array( 'Please', 'opens', 'the door.' ),
				'error_index'  => 1,
				'explanation'  => 'An instruction uses the base verb: "Please open the door."',
			),

			// --- 1.16.0 expansion: A2  --------------------
			array(
				'id'           => 'err-a2-1',
				'topic'        => 'past-tense',
				'level'        => 'A2',
				'segments'     => array( 'I', 'have seen', 'that film', 'last week.' ),
				'error_index'  => 1,
				'explanation'  => 'With a finished time like "last week", use the past simple: "I saw that film last week."',
			),
			array(
				'id'           => 'err-a2-2',
				'topic'        => 'past-tense',
				'level'        => 'A2',
				'segments'     => array( 'She', 'didn’t went', 'to school', 'yesterday.' ),
				'error_index'  => 1,
				'explanation'  => 'After "didn’t", use the base verb: "didn’t go", not "didn’t went".',
			),
			array(
				'id'           => 'err-a2-3',
				'topic'        => 'past-tense',
				'level'        => 'A2',
				'segments'     => array( 'While', 'I', 'was cook', 'dinner,', 'the phone', 'rang.' ),
				'error_index'  => 2,
				'explanation'  => 'The past continuous is "was" + -ing: "was cooking".',
			),
			array(
				'id'           => 'err-a2-4',
				'topic'        => 'past-tense',
				'level'        => 'A2',
				'segments'     => array( 'We', 'catched', 'the last bus', 'home.' ),
				'error_index'  => 1,
				'explanation'  => '"Catch" is irregular: its past simple is "caught", not "catched".',
			),
			array(
				'id'           => 'err-a2-5',
				'topic'        => 'past-tense',
				'level'        => 'A2',
				'segments'     => array( 'I', 'have', 'knew', 'him', 'for years.' ),
				'error_index'  => 2,
				'explanation'  => 'The present perfect needs the past participle: "have known", not "have knew".',
			),
			array(
				'id'           => 'err-a2-6',
				'topic'        => 'prepositions',
				'level'        => 'A2',
				'segments'     => array( 'She', 'has worked', 'here', 'for', '2019.' ),
				'error_index'  => 3,
				'explanation'  => 'Use "since" with a point in time (2019) and "for" with a period: "since 2019".',
			),
			array(
				'id'           => 'err-a2-7',
				'topic'        => 'prepositions',
				'level'        => 'A2',
				'segments'     => array( 'We', 'arrived', 'in', 'the station', 'at six.' ),
				'error_index'  => 2,
				'explanation'  => 'For a building or point such as a station, say "arrive at": "arrived at the station".',
			),
			array(
				'id'           => 'err-a2-8',
				'topic'        => 'prepositions',
				'level'        => 'A2',
				'segments'     => array( 'I’m', 'interested', 'on', 'music.' ),
				'error_index'  => 2,
				'explanation'  => 'The adjective "interested" is followed by "in": "interested in music".',
			),
			array(
				'id'           => 'err-a2-9',
				'topic'        => 'comparatives',
				'level'        => 'A2',
				'segments'     => array( 'This is', 'the most big', 'city', 'in my country.' ),
				'error_index'  => 1,
				'explanation'  => 'Short adjectives form the superlative with -est: "the biggest", not "the most big".',
			),
			array(
				'id'           => 'err-a2-10',
				'topic'        => 'comparatives',
				'level'        => 'A2',
				'segments'     => array( 'My new phone', 'is', 'more better', 'than my old one.' ),
				'error_index'  => 2,
				'explanation'  => '"Better" is already comparative, so "more" is not needed: "is better than".',
			),
			array(
				'id'           => 'err-a2-11',
				'topic'        => 'comparatives',
				'level'        => 'A2',
				'segments'     => array( 'She', 'is', 'as tall', 'than', 'her brother.' ),
				'error_index'  => 3,
				'explanation'  => 'Equal comparisons use "as … as": "as tall as her brother".',
			),
			array(
				'id'           => 'err-a2-12',
				'topic'        => 'future',
				'level'        => 'A2',
				'segments'     => array( 'I', 'will to', 'call you', 'tomorrow.' ),
				'error_index'  => 1,
				'explanation'  => '"Will" is followed by the base verb without "to": "I will call you."',
			),
			array(
				'id'           => 'err-a2-13',
				'topic'        => 'future',
				'level'        => 'A2',
				'segments'     => array( 'Look at the sky!', 'It’s', 'going rain.' ),
				'error_index'  => 2,
				'explanation'  => 'The structure is "going to" + verb: "It’s going to rain."',
			),
			array(
				'id'           => 'err-a2-14',
				'topic'        => 'modals',
				'level'        => 'A2',
				'segments'     => array( 'You', 'don’t must', 'park', 'here.' ),
				'error_index'  => 1,
				'explanation'  => 'The negative of "must" is "mustn’t", not "don’t must".',
			),
			array(
				'id'           => 'err-a2-15',
				'topic'        => 'modals',
				'level'        => 'A2',
				'segments'     => array( 'He', 'musts', 'wear', 'a uniform', 'at work.' ),
				'error_index'  => 1,
				'explanation'  => 'Modal verbs never add -s: "he must", not "he musts".',
			),
			array(
				'id'           => 'err-a2-16',
				'topic'        => 'quantifiers',
				'level'        => 'A2',
				'segments'     => array( 'There', 'aren’t', 'some', 'eggs', 'in the fridge.' ),
				'error_index'  => 2,
				'explanation'  => 'In negative sentences, use "any", not "some": "There aren’t any eggs."',
			),
			array(
				'id'           => 'err-a2-17',
				'topic'        => 'quantifiers',
				'level'        => 'A2',
				'segments'     => array( 'I', 'don’t have', 'many', 'money.' ),
				'error_index'  => 2,
				'explanation'  => '"Money" is uncountable, so use "much", not "many".',
			),
			array(
				'id'           => 'err-a2-18',
				'topic'        => 'agreement',
				'level'        => 'A2',
				'segments'     => array( 'Everybody', 'know', 'the answer.' ),
				'error_index'  => 1,
				'explanation'  => '"Everybody" is singular, so the verb is "knows".',
			),
			array(
				'id'           => 'err-a2-19',
				'topic'        => 'pronouns',
				'level'        => 'A2',
				'segments'     => array( 'They', 'hurt', 'theirselves', 'playing football.' ),
				'error_index'  => 2,
				'explanation'  => 'The reflexive pronoun for "they" is "themselves"; "theirselves" is not standard English.',
			),
			array(
				'id'           => 'err-a2-20',
				'topic'        => 'pronouns',
				'level'        => 'A2',
				'segments'     => array( 'Is', 'this', 'book', 'your?' ),
				'error_index'  => 3,
				'explanation'  => 'Without a noun after it, the possessive is "yours": "Is this book yours?"',
			),
			array(
				'id'           => 'err-a2-21',
				'topic'        => 'question-forms',
				'level'        => 'A2',
				'segments'     => array( 'Where', 'did you went', 'last summer?' ),
				'error_index'  => 1,
				'explanation'  => 'After "did", use the base verb: "Where did you go?"',
			),
			array(
				'id'           => 'err-a2-22',
				'topic'        => 'question-forms',
				'level'        => 'A2',
				'segments'     => array( 'Who’s', 'bag', 'is this?' ),
				'error_index'  => 0,
				'explanation'  => 'To ask who owns something, use "whose"; "who’s" means "who is".',
			),
			array(
				'id'           => 'err-a2-23',
				'topic'        => 'articles',
				'level'        => 'A2',
				'segments'     => array( 'I', 'usually', 'have', 'a breakfast', 'at seven.' ),
				'error_index'  => 3,
				'explanation'  => 'Meals normally take no article: "have breakfast", not "have a breakfast".',
			),
			array(
				'id'           => 'err-a2-24',
				'topic'        => 'gerunds-infinitives',
				'level'        => 'A2',
				'segments'     => array( 'I', 'enjoy', 'to swim', 'in the sea.' ),
				'error_index'  => 2,
				'explanation'  => '"Enjoy" is followed by the -ing form: "I enjoy swimming."',
			),

			// --- 1.16.0 expansion: B1  --------------------
			array(
				'id'           => 'err-b1-1',
				'topic'        => 'past-tense',
				'level'        => 'B1',
				'segments'     => array( 'I', 'have lived', 'in Rome', 'from 2010 to 2015.' ),
				'error_index'  => 1,
				'explanation'  => 'A finished period in the past takes the past simple: "I lived in Rome from 2010 to 2015."',
			),
			array(
				'id'           => 'err-b1-2',
				'topic'        => 'past-tense',
				'level'        => 'B1',
				'segments'     => array( 'When', 'we', 'arrived,', 'the film', 'has', 'already', 'started.' ),
				'error_index'  => 4,
				'explanation'  => 'An action before another past action takes the past perfect: "the film had already started".',
			),
			array(
				'id'           => 'err-b1-3',
				'topic'        => 'past-tense',
				'level'        => 'B1',
				'segments'     => array( 'I', 'use to', 'play', 'the piano', 'as a child.' ),
				'error_index'  => 1,
				'explanation'  => 'For past habits, the form is "used to": "I used to play the piano."',
			),
			array(
				'id'           => 'err-b1-4',
				'topic'        => 'conditionals',
				'level'        => 'B1',
				'segments'     => array( 'If', 'it', 'will rain', 'tomorrow,', 'we’ll stay', 'at home.' ),
				'error_index'  => 2,
				'explanation'  => 'In the "if" clause of a first conditional, use the present simple: "If it rains tomorrow".',
			),
			array(
				'id'           => 'err-b1-5',
				'topic'        => 'conditionals',
				'level'        => 'B1',
				'segments'     => array( 'If', 'I', 'would have', 'more time,', 'I would travel', 'more.' ),
				'error_index'  => 2,
				'explanation'  => 'The "if" clause of a second conditional takes the past simple: "If I had more time".',
			),
			array(
				'id'           => 'err-b1-6',
				'topic'        => 'relative-clauses',
				'level'        => 'B1',
				'segments'     => array( 'That’s', 'the boy', 'who’s', 'bike', 'was stolen.' ),
				'error_index'  => 2,
				'explanation'  => 'Possession needs "whose"; "who’s" means "who is": "the boy whose bike was stolen".',
			),
			array(
				'id'           => 'err-b1-7',
				'topic'        => 'gerunds-infinitives',
				'level'        => 'B1',
				'segments'     => array( 'She', 'decided', 'studying', 'medicine.' ),
				'error_index'  => 2,
				'explanation'  => '"Decide" is followed by the to-infinitive: "decided to study".',
			),
			array(
				'id'           => 'err-b1-8',
				'topic'        => 'gerunds-infinitives',
				'level'        => 'B1',
				'segments'     => array( 'Would', 'you', 'mind', 'to close', 'the window?' ),
				'error_index'  => 3,
				'explanation'  => '"Mind" is followed by the -ing form: "Would you mind closing the window?"',
			),
			array(
				'id'           => 'err-b1-9',
				'topic'        => 'gerunds-infinitives',
				'level'        => 'B1',
				'segments'     => array( 'He', 'is', 'interested', 'in', 'learn', 'Japanese.' ),
				'error_index'  => 4,
				'explanation'  => 'After a preposition such as "in", use the -ing form: "interested in learning".',
			),
			array(
				'id'           => 'err-b1-10',
				'topic'        => 'passive-voice',
				'level'        => 'B1',
				'segments'     => array( 'The letters', 'were send', 'yesterday.' ),
				'error_index'  => 1,
				'explanation'  => 'The passive needs the past participle: "were sent", not "were send".',
			),
			array(
				'id'           => 'err-b1-11',
				'topic'        => 'passive-voice',
				'level'        => 'B1',
				'segments'     => array( 'English', 'is speaking', 'in many countries.' ),
				'error_index'  => 1,
				'explanation'  => 'English does not speak — people speak it — so the passive is needed: "is spoken".',
			),
			array(
				'id'           => 'err-b1-12',
				'topic'        => 'modals',
				'level'        => 'B1',
				'segments'     => array( 'You', 'mustn’t', 'pay —', 'the museum is free.' ),
				'error_index'  => 1,
				'explanation'  => '"Mustn’t" means it is forbidden; for "not necessary", use "don’t have to": "You don’t have to pay."',
			),
			array(
				'id'           => 'err-b1-13',
				'topic'        => 'modals',
				'level'        => 'B1',
				'segments'     => array( 'I', 'must', 'work', 'late yesterday.' ),
				'error_index'  => 1,
				'explanation'  => '"Must" has no past form; past obligation uses "had to": "I had to work late yesterday."',
			),
			array(
				'id'           => 'err-b1-14',
				'topic'        => 'quantifiers',
				'level'        => 'B1',
				'segments'     => array( 'I’ve got', 'a few', 'money', 'left.' ),
				'error_index'  => 1,
				'explanation'  => '"Money" is uncountable, so use "a little", not "a few".',
			),
			array(
				'id'           => 'err-b1-15',
				'topic'        => 'negation',
				'level'        => 'B1',
				'segments'     => array( 'He', 'didn’t', 'eat', 'nothing', 'all day.' ),
				'error_index'  => 3,
				'explanation'  => 'Standard English uses only one negative: "He didn’t eat anything" (or "He ate nothing").',
			),
			array(
				'id'           => 'err-b1-16',
				'topic'        => 'comparatives',
				'level'        => 'B1',
				'segments'     => array( 'The more', 'you practise,', 'more easier', 'it becomes.' ),
				'error_index'  => 2,
				'explanation'  => 'The pattern is "the + comparative, the + comparative": "the easier it becomes".',
			),
			array(
				'id'           => 'err-b1-17',
				'topic'        => 'comparatives',
				'level'        => 'B1',
				'segments'     => array( 'It was', 'the worse', 'day', 'of my life.' ),
				'error_index'  => 1,
				'explanation'  => '"Of my life" needs the superlative: "the worst day", not "the worse day".',
			),
			array(
				'id'           => 'err-b1-18',
				'topic'        => 'articles',
				'level'        => 'B1',
				'segments'     => array( 'The', 'life', 'is', 'full of surprises.' ),
				'error_index'  => 0,
				'explanation'  => 'Abstract nouns used in a general sense take no article: "Life is full of surprises."',
			),
			array(
				'id'           => 'err-b1-19',
				'topic'        => 'prepositions',
				'level'        => 'B1',
				'segments'     => array( 'It', 'depends', 'of', 'the weather.' ),
				'error_index'  => 2,
				'explanation'  => 'The verb "depend" is followed by "on": "It depends on the weather."',
			),
			array(
				'id'           => 'err-b1-20',
				'topic'        => 'prepositions',
				'level'        => 'B1',
				'segments'     => array( 'She’s', 'afraid', 'from', 'spiders.' ),
				'error_index'  => 2,
				'explanation'  => 'The adjective "afraid" is followed by "of": "afraid of spiders".',
			),
			array(
				'id'           => 'err-b1-21',
				'topic'        => 'reported-speech',
				'level'        => 'B1',
				'segments'     => array( 'He', 'told', 'to me', 'that he was tired.' ),
				'error_index'  => 2,
				'explanation'  => '"Tell" takes a direct object without "to": "He told me that he was tired."',
			),
			array(
				'id'           => 'err-b1-22',
				'topic'        => 'linking-words',
				'level'        => 'B1',
				'segments'     => array( 'Despite', 'it was raining,', 'we', 'went out.' ),
				'error_index'  => 0,
				'explanation'  => '"Despite" cannot be followed by a full clause; use "Although it was raining".',
			),
			array(
				'id'           => 'err-b1-23',
				'topic'        => 'agreement',
				'level'        => 'B1',
				'segments'     => array( 'One', 'of my friends', 'live', 'in Canada.' ),
				'error_index'  => 2,
				'explanation'  => 'The subject is "one", which is singular, so the verb is "lives".',
			),
			array(
				'id'           => 'err-b1-24',
				'topic'        => 'past-tense',
				'level'        => 'B1',
				'segments'     => array( 'I', 'have', 'just', 'finish', 'my homework.' ),
				'error_index'  => 3,
				'explanation'  => 'The present perfect needs the past participle: "I have just finished".',
			),

			// --- 1.16.0 expansion: B2  --------------------
			array(
				'id'           => 'err-b2-1',
				'topic'        => 'passive-voice',
				'level'        => 'B2',
				'segments'     => array( 'The winners', 'will announce', 'next week.' ),
				'error_index'  => 1,
				'explanation'  => 'The winners are announced by someone else, so the passive is needed: "will be announced".',
			),
			array(
				'id'           => 'err-b2-2',
				'topic'        => 'passive-voice',
				'level'        => 'B2',
				'segments'     => array( 'My car', 'is repairing', 'at the moment.' ),
				'error_index'  => 1,
				'explanation'  => 'The car does not repair anything; the present continuous passive is "is being repaired".',
			),
			array(
				'id'           => 'err-b2-3',
				'topic'        => 'passive-voice',
				'level'        => 'B2',
				'segments'     => array( 'I', 'was', 'told wait', 'outside.' ),
				'error_index'  => 2,
				'explanation'  => 'The passive of "tell someone to do" is "be told to do": "I was told to wait outside."',
			),
			array(
				'id'           => 'err-b2-4',
				'topic'        => 'conditionals',
				'level'        => 'B2',
				'segments'     => array( 'If', 'you', 'had told', 'me,', 'I', 'would help', 'you.' ),
				'error_index'  => 5,
				'explanation'  => 'A third conditional needs "would have" + past participle: "I would have helped you."',
			),
			array(
				'id'           => 'err-b2-5',
				'topic'        => 'conditionals',
				'level'        => 'B2',
				'segments'     => array( 'I wish', 'I', 'can', 'speak', 'Italian.' ),
				'error_index'  => 2,
				'explanation'  => 'A wish about a present ability uses "could": "I wish I could speak Italian."',
			),
			array(
				'id'           => 'err-b2-6',
				'topic'        => 'conditionals',
				'level'        => 'B2',
				'segments'     => array( 'Unless', 'you', 'don’t hurry,', 'you’ll', 'miss', 'the train.' ),
				'error_index'  => 2,
				'explanation'  => '"Unless" already means "if not", so the verb must be positive: "Unless you hurry".',
			),
			array(
				'id'           => 'err-b2-7',
				'topic'        => 'reported-speech',
				'level'        => 'B2',
				'segments'     => array( 'He asked me', 'what time', 'does the shop open.' ),
				'error_index'  => 2,
				'explanation'  => 'Reported questions use statement word order: "what time the shop opened".',
			),
			array(
				'id'           => 'err-b2-8',
				'topic'        => 'reported-speech',
				'level'        => 'B2',
				'segments'     => array( 'She', 'told me', 'don’t', 'be late.' ),
				'error_index'  => 2,
				'explanation'  => 'A reported negative instruction is "told someone not to": "She told me not to be late."',
			),
			array(
				'id'           => 'err-b2-9',
				'topic'        => 'reported-speech',
				'level'        => 'B2',
				'segments'     => array( 'He', 'suggested', 'us to take', 'a taxi.' ),
				'error_index'  => 2,
				'explanation'  => '"Suggest" is not followed by object + to-infinitive: "He suggested taking a taxi" (or "that we take a taxi").',
			),
			array(
				'id'           => 'err-b2-10',
				'topic'        => 'gerunds-infinitives',
				'level'        => 'B2',
				'segments'     => array( 'I', 'look forward', 'to hear', 'from you.' ),
				'error_index'  => 2,
				'explanation'  => 'In "look forward to", "to" is a preposition, so it is followed by -ing: "to hearing".',
			),
			array(
				'id'           => 'err-b2-11',
				'topic'        => 'gerunds-infinitives',
				'level'        => 'B2',
				'segments'     => array( 'She', 'managed', 'finishing', 'the report', 'on time.' ),
				'error_index'  => 2,
				'explanation'  => '"Manage" is followed by the to-infinitive: "managed to finish".',
			),
			array(
				'id'           => 'err-b2-12',
				'topic'        => 'gerunds-infinitives',
				'level'        => 'B2',
				'segments'     => array( 'She', 'avoided', 'to answer', 'my question.' ),
				'error_index'  => 2,
				'explanation'  => '"Avoid" is followed by the -ing form: "She avoided answering my question."',
			),
			array(
				'id'           => 'err-b2-13',
				'topic'        => 'relative-clauses',
				'level'        => 'B2',
				'segments'     => array( 'The house,', 'that', 'we bought', 'last year,', 'needs', 'a new roof.' ),
				'error_index'  => 1,
				'explanation'  => 'A non-defining clause (between commas) cannot use "that"; use "which".',
			),
			array(
				'id'           => 'err-b2-14',
				'topic'        => 'relative-clauses',
				'level'        => 'B2',
				'segments'     => array( 'That’s', 'the reason', 'because', 'I left.' ),
				'error_index'  => 2,
				'explanation'  => 'After "the reason", use "why" (or "that"), not "because": "the reason why I left".',
			),
			array(
				'id'           => 'err-b2-15',
				'topic'        => 'linking-words',
				'level'        => 'B2',
				'segments'     => array( 'Although', 'his injury,', 'he', 'finished', 'the race.' ),
				'error_index'  => 0,
				'explanation'  => '"Although" needs a full clause; before a noun phrase use "Despite": "Despite his injury".',
			),
			array(
				'id'           => 'err-b2-16',
				'topic'        => 'linking-words',
				'level'        => 'B2',
				'segments'     => array( 'She', 'was', 'late', 'because', 'the traffic.' ),
				'error_index'  => 3,
				'explanation'  => 'Before a noun phrase, use "because of": "late because of the traffic".',
			),
			array(
				'id'           => 'err-b2-17',
				'topic'        => 'linking-words',
				'level'        => 'B2',
				'segments'     => array( 'I’ll take', 'an umbrella', 'in case of', 'it rains.' ),
				'error_index'  => 2,
				'explanation'  => '"In case of" is followed by a noun; before a clause use "in case": "in case it rains".',
			),
			array(
				'id'           => 'err-b2-18',
				'topic'        => 'modals',
				'level'        => 'B2',
				'segments'     => array( 'He', 'must have forget', 'his keys.' ),
				'error_index'  => 1,
				'explanation'  => '"Must have" is followed by the past participle: "must have forgotten".',
			),
			array(
				'id'           => 'err-b2-19',
				'topic'        => 'modals',
				'level'        => 'B2',
				'segments'     => array( 'They', 'had better to', 'leave', 'now.' ),
				'error_index'  => 1,
				'explanation'  => '"Had better" is followed by the base verb without "to": "They had better leave now."',
			),
			array(
				'id'           => 'err-b2-20',
				'topic'        => 'quantifiers',
				'level'        => 'B2',
				'segments'     => array( 'I', 'have', 'fewer', 'time', 'than I thought.' ),
				'error_index'  => 2,
				'explanation'  => '"Time" is uncountable here, so use "less", not "fewer".',
			),
			array(
				'id'           => 'err-b2-21',
				'topic'        => 'articles',
				'level'        => 'B2',
				'segments'     => array( 'The', 'honesty', 'is', 'the best policy.' ),
				'error_index'  => 0,
				'explanation'  => 'An abstract noun used in a general sense takes no article: "Honesty is the best policy."',
			),
			array(
				'id'           => 'err-b2-22',
				'topic'        => 'gerunds-infinitives',
				'level'        => 'B2',
				'segments'     => array( 'He', 'insisted', 'to pay', 'for dinner.' ),
				'error_index'  => 2,
				'explanation'  => '"Insist" is followed by "on" + -ing: "He insisted on paying."',
			),
			array(
				'id'           => 'err-b2-23',
				'topic'        => 'agreement',
				'level'        => 'B2',
				'segments'     => array( 'The information', 'you gave me', 'were', 'very useful.' ),
				'error_index'  => 2,
				'explanation'  => '"Information" is uncountable and takes a singular verb: "was very useful".',
			),
			array(
				'id'           => 'err-b2-24',
				'topic'        => 'comparatives',
				'level'        => 'B2',
				'segments'     => array( 'The film', 'was', 'much more better', 'than I expected.' ),
				'error_index'  => 2,
				'explanation'  => '"Better" is already comparative, so drop "more": "much better than I expected".',
			),

			// --- 1.16.0 expansion: C1  --------------------
			array(
				'id'           => 'err-c1-1',
				'topic'        => 'passive-voice',
				'level'        => 'C1',
				'segments'     => array( 'He', 'is believed', 'to leave', 'the country', 'last week.' ),
				'error_index'  => 2,
				'explanation'  => 'An action earlier than the believing needs the perfect infinitive: "is believed to have left".',
			),
			array(
				'id'           => 'err-c1-2',
				'topic'        => 'passive-voice',
				'level'        => 'C1',
				'segments'     => array( 'I', 'had', 'my hair', 'cutting', 'yesterday.' ),
				'error_index'  => 3,
				'explanation'  => 'The causative "have something done" uses the past participle: "had my hair cut".',
			),
			array(
				'id'           => 'err-c1-3',
				'topic'        => 'inversion',
				'level'        => 'C1',
				'segments'     => array( 'Hardly', 'I had', 'sat down', 'when the phone rang.' ),
				'error_index'  => 1,
				'explanation'  => 'After "Hardly" at the start of a sentence, invert the subject and auxiliary: "Hardly had I sat down".',
			),
			array(
				'id'           => 'err-c1-4',
				'topic'        => 'inversion',
				'level'        => 'C1',
				'segments'     => array( 'Not only', 'she sings,', 'but she also dances.' ),
				'error_index'  => 1,
				'explanation'  => 'After "Not only" at the start, use inversion: "Not only does she sing".',
			),
			array(
				'id'           => 'err-c1-5',
				'topic'        => 'conditionals',
				'level'        => 'C1',
				'segments'     => array( 'But for', 'your help,', 'I', 'would fail', 'last year.' ),
				'error_index'  => 3,
				'explanation'  => 'A past situation with "but for" needs "would have" + past participle: "would have failed".',
			),
			array(
				'id'           => 'err-c1-6',
				'topic'        => 'conditionals',
				'level'        => 'C1',
				'segments'     => array( 'Supposing', 'you', 'will lose', 'your job,', 'what would you do?' ),
				'error_index'  => 2,
				'explanation'  => 'An imaginary situation after "supposing" takes the past simple: "Supposing you lost your job".',
			),
			array(
				'id'           => 'err-c1-7',
				'topic'        => 'reported-speech',
				'level'        => 'C1',
				'segments'     => array( 'He', 'denied', 'to steal', 'the money.' ),
				'error_index'  => 2,
				'explanation'  => '"Deny" is followed by the -ing form: "He denied stealing the money."',
			),
			array(
				'id'           => 'err-c1-8',
				'topic'        => 'reported-speech',
				'level'        => 'C1',
				'segments'     => array( 'She', 'accused', 'him', 'for lying.' ),
				'error_index'  => 3,
				'explanation'  => '"Accuse" takes "of": "She accused him of lying."',
			),
			array(
				'id'           => 'err-c1-9',
				'topic'        => 'reported-speech',
				'level'        => 'C1',
				'segments'     => array( 'They', 'advised', 'me not going', 'there.' ),
				'error_index'  => 2,
				'explanation'  => '"Advise" takes object + (not) to-infinitive: "They advised me not to go there."',
			),
			array(
				'id'           => 'err-c1-10',
				'topic'        => 'relative-clauses',
				'level'        => 'C1',
				'segments'     => array( 'She has', 'two brothers,', 'both of', 'who', 'are doctors.' ),
				'error_index'  => 3,
				'explanation'  => 'After a preposition such as "of", the relative pronoun for people is "whom": "both of whom".',
			),
			array(
				'id'           => 'err-c1-11',
				'topic'        => 'relative-clauses',
				'level'        => 'C1',
				'segments'     => array( 'That', 'surprised me most', 'was', 'his calm reaction.' ),
				'error_index'  => 0,
				'explanation'  => 'The subject meaning "the thing that" is "What": "What surprised me most was…"',
			),
			array(
				'id'           => 'err-c1-12',
				'topic'        => 'relative-clauses',
				'level'        => 'C1',
				'segments'     => array( 'He failed', 'the test,', 'what', 'disappointed', 'his parents.' ),
				'error_index'  => 2,
				'explanation'  => 'A clause commenting on a whole previous clause uses "which", not "what".',
			),
			array(
				'id'           => 'err-c1-13',
				'topic'        => 'gerunds-infinitives',
				'level'        => 'C1',
				'segments'     => array( 'There’s', 'no point', 'to argue', 'with him.' ),
				'error_index'  => 2,
				'explanation'  => 'The fixed expression is "there’s no point (in) doing": "no point arguing with him".',
			),
			array(
				'id'           => 'err-c1-14',
				'topic'        => 'gerunds-infinitives',
				'level'        => 'C1',
				'segments'     => array( 'It’s', 'worth', 'to visit', 'the old town.' ),
				'error_index'  => 2,
				'explanation'  => '"Worth" is followed by the -ing form: "It’s worth visiting the old town."',
			),
			array(
				'id'           => 'err-c1-15',
				'topic'        => 'linking-words',
				'level'        => 'C1',
				'segments'     => array( 'In spite', 'the rain,', 'the match', 'went ahead.' ),
				'error_index'  => 0,
				'explanation'  => 'The linker is "in spite of" + noun phrase: "In spite of the rain".',
			),
			array(
				'id'           => 'err-c1-16',
				'topic'        => 'linking-words',
				'level'        => 'C1',
				'segments'     => array( 'Not only', 'is he clever', 'and also', 'very kind.' ),
				'error_index'  => 2,
				'explanation'  => 'The paired structure is "not only … but also": "Not only is he clever but also very kind."',
			),
			array(
				'id'           => 'err-c1-17',
				'topic'        => 'agreement',
				'level'        => 'C1',
				'segments'     => array( 'The number', 'of applicants', 'have', 'increased.' ),
				'error_index'  => 2,
				'explanation'  => '"The number of" is singular, so the verb is "has increased".',
			),
			array(
				'id'           => 'err-c1-18',
				'topic'        => 'agreement',
				'level'        => 'C1',
				'segments'     => array( 'A number', 'of students', 'was', 'absent', 'today.' ),
				'error_index'  => 2,
				'explanation'  => '"A number of" means "several" and takes a plural verb: "were absent".',
			),
			array(
				'id'           => 'err-c1-19',
				'topic'        => 'quantifiers',
				'level'        => 'C1',
				'segments'     => array( 'Hardly', 'nobody', 'came', 'to the party.' ),
				'error_index'  => 1,
				'explanation'  => '"Hardly" is already negative, so it is followed by "anybody": "Hardly anybody came."',
			),
			array(
				'id'           => 'err-c1-20',
				'topic'        => 'past-tense',
				'level'        => 'C1',
				'segments'     => array( 'By the time', 'she', 'arrived,', 'we', 'have been waiting', 'for an hour.' ),
				'error_index'  => 4,
				'explanation'  => 'Duration up to a past moment uses the past perfect continuous: "we had been waiting".',
			),
			array(
				'id'           => 'err-c1-21',
				'topic'        => 'future',
				'level'        => 'C1',
				'segments'     => array( 'I', 'will have', 'finish', 'the report', 'by Friday.' ),
				'error_index'  => 2,
				'explanation'  => 'The future perfect is "will have" + past participle: "I will have finished the report by Friday."',
			),
			array(
				'id'           => 'err-c1-22',
				'topic'        => 'conditionals',
				'level'        => 'C1',
				'segments'     => array( 'It’s', 'high time', 'we', 'leave.' ),
				'error_index'  => 3,
				'explanation'  => '"It’s high time" + subject is followed by the past simple: "It’s high time we left."',
			),
			array(
				'id'           => 'err-c1-23',
				'topic'        => 'prepositions',
				'level'        => 'C1',
				'segments'     => array( 'She', 'has', 'a talent', 'in', 'music.' ),
				'error_index'  => 3,
				'explanation'  => 'The noun "talent" is followed by "for": "a talent for music".',
			),
			array(
				'id'           => 'err-c1-24',
				'topic'        => 'prepositions',
				'level'        => 'C1',
				'segments'     => array( 'The decision', 'was based', 'in', 'the evidence.' ),
				'error_index'  => 2,
				'explanation'  => '"Based" is followed by "on": "based on the evidence".',
			),

			// --- 1.16.0 expansion: C2  --------------------
			array(
				'id'           => 'err-c2-1',
				'topic'        => 'inversion',
				'level'        => 'C2',
				'segments'     => array( 'Never', 'I have seen', 'such chaos.' ),
				'error_index'  => 1,
				'explanation'  => 'After a negative adverb such as "Never" at the start, invert: "Never have I seen such chaos."',
			),
			array(
				'id'           => 'err-c2-2',
				'topic'        => 'inversion',
				'level'        => 'C2',
				'segments'     => array( 'Little', 'she knew', 'that she was being followed.' ),
				'error_index'  => 1,
				'explanation'  => '"Little" at the start of a sentence requires inversion: "Little did she know".',
			),
			array(
				'id'           => 'err-c2-3',
				'topic'        => 'inversion',
				'level'        => 'C2',
				'segments'     => array( 'Only after', 'the meeting', 'I realised', 'the problem.' ),
				'error_index'  => 2,
				'explanation'  => '"Only after …" at the start triggers inversion: "did I realise".',
			),
			array(
				'id'           => 'err-c2-4',
				'topic'        => 'inversion',
				'level'        => 'C2',
				'segments'     => array( 'No sooner', 'had we left', 'when', 'it started to rain.' ),
				'error_index'  => 2,
				'explanation'  => '"No sooner" pairs with "than", not "when": "No sooner had we left than it started to rain."',
			),
			array(
				'id'           => 'err-c2-5',
				'topic'        => 'inversion',
				'level'        => 'C2',
				'segments'     => array( 'Under no circumstances', 'you should', 'open', 'this door.' ),
				'error_index'  => 1,
				'explanation'  => 'A negative phrase at the start requires inversion: "Under no circumstances should you open this door."',
			),
			array(
				'id'           => 'err-c2-6',
				'topic'        => 'conditionals',
				'level'        => 'C2',
				'segments'     => array( 'Had', 'it not', 'be', 'for her,', 'we’d have failed.' ),
				'error_index'  => 2,
				'explanation'  => 'The inverted form is "Had it not been for her", with the past participle "been".',
			),
			array(
				'id'           => 'err-c2-7',
				'topic'        => 'conditionals',
				'level'        => 'C2',
				'segments'     => array( 'Were', 'she', 'know', 'the truth,', 'she’d be furious.' ),
				'error_index'  => 2,
				'explanation'  => 'In an inverted "were" conditional, the verb follows as a to-infinitive: "Were she to know the truth".',
			),
			array(
				'id'           => 'err-c2-8',
				'topic'        => 'passive-voice',
				'level'        => 'C2',
				'segments'     => array( 'The bridge', 'is thought', 'to be built', 'in the 12th century.' ),
				'error_index'  => 2,
				'explanation'  => 'A past action the bridge received needs the perfect passive infinitive: "to have been built".',
			),
			array(
				'id'           => 'err-c2-9',
				'topic'        => 'passive-voice',
				'level'        => 'C2',
				'segments'     => array( 'He', 'objects', 'to', 'treat', 'like a child.' ),
				'error_index'  => 3,
				'explanation'  => 'He is the one treated, and "to" here is a preposition, so the passive gerund is needed: "objects to being treated".',
			),
			array(
				'id'           => 'err-c2-10',
				'topic'        => 'reported-speech',
				'level'        => 'C2',
				'segments'     => array( 'She', 'denied', 'ever', 'to have met', 'him.' ),
				'error_index'  => 3,
				'explanation'  => '"Deny" is followed by the -ing form: "denied ever having met him".',
			),
			array(
				'id'           => 'err-c2-11',
				'topic'        => 'relative-clauses',
				'level'        => 'C2',
				'segments'     => array( 'The film,', 'the ending', 'of what', 'I found', 'disappointing,', 'won awards.' ),
				'error_index'  => 2,
				'explanation'  => 'The correct relative form for things after a noun is "of which": "the ending of which I found disappointing".',
			),
			array(
				'id'           => 'err-c2-12',
				'topic'        => 'relative-clauses',
				'level'        => 'C2',
				'segments'     => array( 'He’s', 'the only person', 'on', 'who', 'I can rely.' ),
				'error_index'  => 3,
				'explanation'  => 'After a preposition, the relative pronoun for people is "whom": "on whom I can rely".',
			),
			array(
				'id'           => 'err-c2-13',
				'topic'        => 'relative-clauses',
				'level'        => 'C2',
				'segments'     => array( 'She gave two reasons,', 'neither', 'of', 'them', 'convinced me.' ),
				'error_index'  => 3,
				'explanation'  => 'To join the clauses into one sentence, use a relative pronoun: "neither of which convinced me".',
			),
			array(
				'id'           => 'err-c2-14',
				'topic'        => 'linking-words',
				'level'        => 'C2',
				'segments'     => array( 'Strangely', 'as it may seem,', 'the story', 'is true.' ),
				'error_index'  => 0,
				'explanation'  => 'The concessive pattern uses the adjective: "Strange as it may seem".',
			),
			array(
				'id'           => 'err-c2-15',
				'topic'        => 'linking-words',
				'level'        => 'C2',
				'segments'     => array( 'The plan', 'was approved,', 'despite', 'some members', 'voted against it.' ),
				'error_index'  => 2,
				'explanation'  => '"Despite" cannot introduce a full clause; use "although": "although some members voted against it".',
			),
			array(
				'id'           => 'err-c2-16',
				'topic'        => 'prepositions',
				'level'        => 'C2',
				'segments'     => array( 'His success', 'is attributable', 'for', 'hard work.' ),
				'error_index'  => 2,
				'explanation'  => '"Attributable" is followed by "to": "attributable to hard work".',
			),
			array(
				'id'           => 'err-c2-17',
				'topic'        => 'prepositions',
				'level'        => 'C2',
				'segments'     => array( 'The deal', 'is subject', 'for', 'approval.' ),
				'error_index'  => 2,
				'explanation'  => 'The phrase is "subject to": "The deal is subject to approval."',
			),
			array(
				'id'           => 'err-c2-18',
				'topic'        => 'prepositions',
				'level'        => 'C2',
				'segments'     => array( 'He', 'was accused', 'for', 'leaking', 'secrets.' ),
				'error_index'  => 2,
				'explanation'  => '"Accuse" takes "of": "He was accused of leaking secrets."',
			),
			array(
				'id'           => 'err-c2-19',
				'topic'        => 'agreement',
				'level'        => 'C2',
				'segments'     => array( 'The majority', 'of the evidence', 'point', 'to his guilt.' ),
				'error_index'  => 2,
				'explanation'  => 'With "the majority of" + an uncountable noun, the verb is singular: "points".',
			),
			array(
				'id'           => 'err-c2-20',
				'topic'        => 'agreement',
				'level'        => 'C2',
				'segments'     => array( 'Ten miles', 'are', 'a long way', 'to walk.' ),
				'error_index'  => 1,
				'explanation'  => 'A distance treated as a single amount takes a singular verb: "Ten miles is a long way."',
			),
			array(
				'id'           => 'err-c2-21',
				'topic'        => 'comparatives',
				'level'        => 'C2',
				'segments'     => array( 'He', 'is', 'the more intelligent', 'of the three.' ),
				'error_index'  => 2,
				'explanation'  => 'With three or more, use the superlative: "the most intelligent of the three".',
			),
			array(
				'id'           => 'err-c2-22',
				'topic'        => 'articles',
				'level'        => 'C2',
				'segments'     => array( 'It was', 'a', 'honour', 'to meet you.' ),
				'error_index'  => 1,
				'explanation'  => 'The "h" in "honour" is silent, so it takes "an": "an honour".',
			),
			array(
				'id'           => 'err-c2-23',
				'topic'        => 'gerunds-infinitives',
				'level'        => 'C2',
				'segments'     => array( 'I', 'can’t help', 'to think', 'he’s hiding something.' ),
				'error_index'  => 2,
				'explanation'  => '"Can’t help" is followed by the -ing form: "I can’t help thinking".',
			),
			array(
				'id'           => 'err-c2-24',
				'topic'        => 'modals',
				'level'        => 'C2',
				'segments'     => array( 'You', 'had better not to', 'be', 'late.' ),
				'error_index'  => 1,
				'explanation'  => '"Had better not" is followed by the base verb without "to": "You had better not be late."',
			),
		);
	}

	/** Topic slugs to display labels. */
	private const TOPIC_LABELS = array(
		'articles'         => 'Articles',
		'prepositions'     => 'Prepositions',
		'present-tense'    => 'Present tense',
		'past-tense'       => 'Past tense',
		'comparatives'     => 'Comparatives',
		'agreement'        => 'Subject-verb agreement',
		'modals'           => 'Modal verbs',
		'quantifiers'      => 'Quantifiers',
		'passive-voice'    => 'Passive voice',
		'reported-speech'  => 'Reported speech',
		'conditionals'     => 'Conditionals',
		'relative-clauses' => 'Relative clauses',
		'plurals'             => 'Plurals',
		'verb-forms'          => 'Verb forms',
		'pronouns'            => 'Pronouns',
		'future'              => 'Future forms',
		'question-forms'      => 'Question forms',
		'gerunds-infinitives' => 'Gerunds and infinitives',
		'negation'            => 'Negatives',
		'linking-words'       => 'Linking words',
		'inversion'           => 'Inversion',
	);

	public static function topic_label( string $topic ): string {
		return self::TOPIC_LABELS[ $topic ] ?? $topic;
	}

	/**
	 * Items at one level, or every item when the level is empty.
	 *
	 * @return list<array{id:string,topic:string,level:string,segments:list<string>,error_index:int,explanation:string}>
	 */
	public static function by_level( string $level ): array {
		if ( '' === $level ) {
			return self::items();
		}

		return array_values(
			array_filter(
				self::items(),
				static fn ( array $item ): bool => $item['level'] === $level
			)
		);
	}

	/**
	 * Levels actually present in the bank, in CEFR order.
	 *
	 * @return list<string>
	 */
	public static function available_levels(): array {
		$present = array();
		foreach ( self::items() as $item ) {
			$present[ $item['level'] ] = true;
		}

		return array_values(
			array_intersect(
				array( 'A1', 'A2', 'B1', 'B2', 'C1', 'C2' ),
				array_keys( $present )
			)
		);
	}
}
