<?php
/**
 * Add CEFR level columns to the shared words table.
 *
 * Two columns, not one. `cefr_level` holds the band; `cefr_source` records
 * whether it was hand-assigned by linguists or inferred algorithmically.
 *
 * The distinction is not decoration. Roughly 7,000 words carry levels assigned
 * by researchers (CEFR-J); the rest are inferred from frequency and word-family
 * data. Presenting both identically would pass an estimate off as authoritative
 * on a site teachers use, and there would be no way to tell them apart later
 * without reimporting.
 *
 * @package EnglishFindersCore
 */

declare(strict_types=1);

namespace EnglishFindersCore\Database;

use EnglishFindersCore\Contracts\MigrationInterface;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

final class CefrColumnsMigration implements MigrationInterface {
	public function version(): string {
		return '1.3.0';
	}

	public function description(): string {
		return 'Add cefr_level and cefr_source columns to the words table.';
	}

	public function up(): void {
		global $wpdb;

		$table = Schema::shared_table( 'words' );

		/*
		 * dbDelta is not used here. It compares a full CREATE TABLE statement
		 * against the live schema, which would mean restating every column of a
		 * large table to add two — and any drift between that restatement and
		 * reality risks unintended ALTERs against live dictionary data. A
		 * targeted ALTER changes exactly what it says it changes.
		 */
		foreach ( $this->columns() as $column => $definition ) {
			if ( $this->column_exists( $table, $column ) ) {
				continue;
			}
			// phpcs:ignore WordPress.DB.PreparedSQL.InterpolatedNotPrepared, WordPress.DB.DirectDatabaseQuery.SchemaChange
			$wpdb->query( "ALTER TABLE {$table} ADD COLUMN {$column} {$definition}" );
		}

		if ( ! $this->index_exists( $table, 'cefr_level' ) ) {
			// Filtering by level must use the index rather than scanning 64k rows.
			// phpcs:ignore WordPress.DB.PreparedSQL.InterpolatedNotPrepared, WordPress.DB.DirectDatabaseQuery.SchemaChange
			$wpdb->query( "ALTER TABLE {$table} ADD INDEX cefr_level (cefr_level)" );
		}
	}

	/**
	 * Rollback drops the columns.
	 *
	 * Safe because they hold imported reference data that can be regenerated by
	 * re-running the import — no user-authored content is lost.
	 */
	public function down(): void {
		global $wpdb;

		$table = Schema::shared_table( 'words' );

		foreach ( array_keys( $this->columns() ) as $column ) {
			if ( ! $this->column_exists( $table, $column ) ) {
				continue;
			}
			// phpcs:ignore WordPress.DB.PreparedSQL.InterpolatedNotPrepared, WordPress.DB.DirectDatabaseQuery.SchemaChange
			$wpdb->query( "ALTER TABLE {$table} DROP COLUMN {$column}" );
		}
	}

	/** @return array<string,string> */
	private function columns(): array {
		return array(
			// varchar rather than an enum: a stored value that no longer matches
			// the allowed set is far easier to inspect and correct than an enum
			// silently coercing it.
			'cefr_level'  => "varchar(2) NOT NULL DEFAULT ''",
			'cefr_source' => "varchar(16) NOT NULL DEFAULT ''",
		);
	}

	private function column_exists( string $table, string $column ): bool {
		global $wpdb;

		$found = $wpdb->get_var(
			$wpdb->prepare(
				// phpcs:ignore WordPress.DB.PreparedSQL.InterpolatedNotPrepared -- Table name is prefix-derived.
				"SHOW COLUMNS FROM {$table} LIKE %s",
				$column
			)
		);

		return is_string( $found ) && '' !== $found;
	}

	private function index_exists( string $table, string $index ): bool {
		global $wpdb;

		$found = $wpdb->get_var(
			$wpdb->prepare(
				// phpcs:ignore WordPress.DB.PreparedSQL.InterpolatedNotPrepared -- Table name is prefix-derived.
				"SHOW INDEX FROM {$table} WHERE Key_name = %s",
				$index
			)
		);

		return null !== $found;
	}
}
