<?php
/**
 * Add sense-level CEFR columns, and seed the first cross-checked batch.
 *
 * `wuc_words.cefr_level` tags one level per headword, but a headword is not
 * one word: "shed" is A2 as a garden building and C1 as "to shed light on."
 * Tagging the whole word C1 (as a word-level-only source would) makes the
 * badge wrong for the sense a beginner is actually looking up. This migration
 * gives `wuc_word_senses` its own `cefr_level`/`cefr_source` pair so a sense
 * can carry a level the headword itself does not.
 *
 * The seed data below is not the full CEFR bridge backlog -- it is the
 * specific set of (word, part_of_speech) pairs that were cross-checked
 * against the Octanove C1/C2 vocabulary profile (CC BY-SA 4.0) *and* against
 * this dictionary's own stored sense definitions, to rule out a part of
 * speech that still mixes a basic and an advanced sense (e.g. "wing" as noun
 * covers both a bird's wing and a political wing, so it was excluded rather
 * than guessed at). Only pairs where every stored sense under that part of
 * speech was judged consistent were kept. See the CEFR data-quality work
 * referenced in project memory for the full audit trail.
 *
 * @package EnglishFindersCore
 */

declare(strict_types=1);

namespace EnglishFindersCore\Database;

use EnglishFindersCore\Contracts\MigrationInterface;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

final class SenseCefrColumnsMigration implements MigrationInterface {
	public function version(): string {
		return '1.4.0';
	}

	public function description(): string {
		return 'Add cefr_level and cefr_source columns to word_senses, and seed a cross-checked sense-level backfill.';
	}

	public function up(): void {
		global $wpdb;

		$table = Schema::shared_table( 'word_senses' );

		foreach ( $this->columns() as $column => $definition ) {
			if ( $this->column_exists( $table, $column ) ) {
				continue;
			}
			// phpcs:ignore WordPress.DB.PreparedSQL.InterpolatedNotPrepared, WordPress.DB.DirectDatabaseQuery.SchemaChange
			$wpdb->query( "ALTER TABLE {$table} ADD COLUMN {$column} {$definition}" );
		}

		if ( ! $this->index_exists( $table, 'cefr_level' ) ) {
			// phpcs:ignore WordPress.DB.PreparedSQL.InterpolatedNotPrepared, WordPress.DB.DirectDatabaseQuery.SchemaChange
			$wpdb->query( "ALTER TABLE {$table} ADD INDEX cefr_level (cefr_level)" );
		}

		$this->seed();
	}

	/**
	 * Columns are safe to drop -- seed data can be regenerated by re-running
	 * this migration, and nothing else writes to these columns yet.
	 */
	public function down(): void {
		global $wpdb;

		$table = Schema::shared_table( 'word_senses' );

		foreach ( array_keys( $this->columns() ) as $column ) {
			if ( ! $this->column_exists( $table, $column ) ) {
				continue;
			}
			// phpcs:ignore WordPress.DB.PreparedSQL.InterpolatedNotPrepared, WordPress.DB.DirectDatabaseQuery.SchemaChange
			$wpdb->query( "ALTER TABLE {$table} DROP COLUMN {$column}" );
		}
	}

	/** @return array<string,string> */
	private function columns(): array {
		return array(
			'cefr_level'  => "varchar(2) NOT NULL DEFAULT ''",
			'cefr_source' => "varchar(16) NOT NULL DEFAULT ''",
		);
	}

	/**
	 * Tag every sense row sharing (word, part_of_speech) with the seeded
	 * level -- the template groups definitions by part of speech, so this is
	 * exactly the granularity a reader sees. Only rows whose word/POS pair
	 * exists are touched; a pair with no matching sense is a harmless no-op,
	 * not an error, since the source dataset and this dictionary were built
	 * independently.
	 */
	private function seed(): void {
		global $wpdb;

		$words_table  = Schema::shared_table( 'words' );
		$senses_table = Schema::shared_table( 'word_senses' );

		foreach ( $this->seed_data() as list( $word, $pos, $level ) ) {
			$word_id = (int) $wpdb->get_var(
				$wpdb->prepare(
					// phpcs:ignore WordPress.DB.PreparedSQL.InterpolatedNotPrepared
					"SELECT id FROM {$words_table} WHERE normalized = %s AND language = 'en'",
					$word
				)
			);
			if ( $word_id < 1 ) {
				continue;
			}
			$wpdb->query(
				$wpdb->prepare(
					// phpcs:ignore WordPress.DB.PreparedSQL.InterpolatedNotPrepared
					"UPDATE {$senses_table} SET cefr_level = %s, cefr_source = 'octanove', updated_at = %s WHERE word_id = %d AND part_of_speech = %s",
					$level,
					current_time( 'mysql', true ),
					$word_id,
					$pos
				)
			);
		}
	}

	/** @return list<array{0:string,1:string,2:string}> */
	private function seed_data(): array {
		return array(
			array( 'absolute', 'noun', 'C1' ),
			array( 'agency', 'noun', 'C2' ),
			array( 'ally', 'verb', 'C2' ),
			array( 'anchor', 'verb', 'C1' ),
			array( 'automatic', 'verb', 'C1' ),
			array( 'automatically', 'adverb', 'C1' ),
			array( 'bald', 'verb', 'C1' ),
			array( 'behind', 'preposition', 'C1' ),
			array( 'bloom', 'verb', 'C1' ),
			array( 'boast', 'noun', 'C1' ),
			array( 'brief', 'verb', 'C1' ),
			array( 'brief', 'noun', 'C2' ),
			array( 'burst', 'noun', 'C1' ),
			array( 'chart', 'verb', 'C1' ),
			array( 'class', 'verb', 'C1' ),
			array( 'contest', 'verb', 'C1' ),
			array( 'contract', 'verb', 'C1' ),
			array( 'craft', 'verb', 'C1' ),
			array( 'deliberate', 'verb', 'C2' ),
			array( 'dependent', 'noun', 'C1' ),
			array( 'desert', 'verb', 'C1' ),
			array( 'engineer', 'verb', 'C1' ),
			array( 'exact', 'verb', 'C2' ),
			array( 'exhaust', 'verb', 'C1' ),
			array( 'exploit', 'verb', 'C1' ),
			array( 'firm', 'verb', 'C1' ),
			array( 'ground', 'verb', 'C1' ),
			array( 'hanging', 'noun', 'C1' ),
			array( 'harvest', 'verb', 'C1' ),
			array( 'house', 'verb', 'C1' ),
			array( 'idle', 'verb', 'C2' ),
			array( 'institute', 'verb', 'C1' ),
			array( 'landscape', 'verb', 'C1' ),
			array( 'lodge', 'verb', 'C1' ),
			array( 'man', 'verb', 'C1' ),
			array( 'orphan', 'verb', 'C1' ),
			array( 'pace', 'verb', 'C1' ),
			array( 'pedestrian', 'adjective', 'C2' ),
			array( 'perfect', 'verb', 'C1' ),
			array( 'plague', 'verb', 'C1' ),
			array( 'pluck', 'noun', 'C2' ),
			array( 'plum', 'adjective', 'C2' ),
			array( 'puzzle', 'verb', 'C1' ),
			array( 'recall', 'noun', 'C1' ),
			array( 'redundant', 'adjective', 'C2' ),
			array( 'scramble', 'noun', 'C1' ),
			array( 'secure', 'verb', 'C2' ),
			array( 'shed', 'verb', 'C1' ),
			array( 'signal', 'verb', 'C1' ),
			array( 'sketch', 'noun', 'C1' ),
			array( 'stock', 'verb', 'C1' ),
			array( 'temper', 'verb', 'C2' ),
			array( 'tone', 'verb', 'C1' ),
			array( 'usher', 'noun', 'C1' ),
			array( 'utility', 'noun', 'C2' ),
			array( 'venture', 'noun', 'C2' ),
			array( 'voice', 'verb', 'C1' ),
		);
	}

	private function column_exists( string $table, string $column ): bool {
		global $wpdb;

		$found = $wpdb->get_var(
			$wpdb->prepare(
				// phpcs:ignore WordPress.DB.PreparedSQL.InterpolatedNotPrepared -- Table name is prefix-derived.
				"SHOW COLUMNS FROM {$table} LIKE %s",
				$column
			)
		);

		return is_string( $found ) && '' !== $found;
	}

	private function index_exists( string $table, string $index ): bool {
		global $wpdb;

		$found = $wpdb->get_var(
			$wpdb->prepare(
				// phpcs:ignore WordPress.DB.PreparedSQL.InterpolatedNotPrepared -- Table name is prefix-derived.
				"SHOW INDEX FROM {$table} WHERE Key_name = %s",
				$index
			)
		);

		return null !== $found;
	}
}
